### ISSUE TITLE
`cluster.local` cannot be used as a pointer to the local trust domain

### ISSUE THREAD

**Issue by rinormaloku** [istio/ztunnel#1260]
When using sidecars, with istio installations that have a custom trust domain, for example `old-td` .
Then both principals  trust domains `old-td` and or `cluster.local` are valid to be used in the Authorization policy
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: service-httpbin.default.svc.cluster.local
  namespace: default
spec:
  rules:
  - from:
    - source:
        principals:
        - old-td/ns/sleep-allow/sa/sleep 
        # or 
        # - cluster.local/ns/sleep-allow/sa/sleep
```

However, that is not the case in ambient (ztunnel), you have to use only the custom trust domain i.e. `old-td`

The docs recommend using `cluster.local` as a [best practice](https://istio.io/latest/docs/tasks/security/authorization/authz-td-migration/#best-practices) (that might be an outdated suggestion, fwiw). However, this means that all customers that were using `cluster.local` as a pointer to the local trust domain, would be impacted when migrating workloads from sidecars into ambient, which would catch them by surprise.
