### ISSUE TITLE
Improper DNS handling of wildcard SE with fqdn endpoints

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#1485]
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-svc-https
  namespace: egress
spec:
  addresses: [240.240.1.1] # Workaround auto-allocator ignoring the wildcard host
  endpoints:
  - address: httpbin.org # Always resolve this
  hosts:
  - '*.httpbin.org' # match this
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```

This doesn't resolve properly. TODO: add some details, wanted to write this before I forgot
