### ISSUE TITLE
pg_basebackup connectivity issues

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#1538]
Tracking issue for reports on this.

**Comment by howardjohn** [comment]
Reproducer:

```
# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: primary
  template:
    metadata:
      labels:
        app: postgres
        role: primary
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "testdb"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc-primary

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "testdb"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc-replica

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-primary
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  selector:
    app: postgres
    role: primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
```

```
PRIMARY_POD=$(kubectl get pods -l role=primary -o jsonpath='{.items[0].metadata.name}')
kubectl exec -it $PRIMARY_POD -- bash -c "
psql -U postgres -d testdb -c \"
CREATE TABLE junk_data AS 
SELECT 
  generate_series(1, 10000000) AS id,
  md5(random()::text) AS random_string,
  (array['foo', 'bar', 'baz'])[floor(random()*3+1)] AS random_choice,
  random() AS random_value;
\"
"
kubectl exec -it $PRIMARY_POD -- bash -c "
echo \"wal_level = replica\" >> /var/lib/postgresql/data/postgresql.conf
echo \"max_wal_senders = 10\" >> /var/lib/postgresql/data/postgresql.conf
echo \"wal_keep_size = 1GB\" >> /var/lib/postgresql/data/postgresql.conf
echo \"host replication postgres 0.0.0.0/0 md5\" >> /var/lib/postgresql/data/pg_hba.conf
"
kubectl exec -it $PRIMARY_POD -- bash -c "pg_ctl restart -D /var/lib/postgresql/data"
REPLICA_POD=$(kubectl get pods -l role=replica -o jsonpath='{.items[0].metadata.name}')
```

on replica:
```
 rm -rf /var/lib/postgresql/data/*;  echo mysecretpassword | pg_basebackup -h postgres-primary -U postgres -D /var/lib/postgresql/data -P -R -X stream  --checkpoint=fast
```

Happens >50% of the time for me if both are in the mesh
