### ISSUE TITLE
support on-demand hostname for workloads

### ISSUE THREAD

**Issue by kdorosh** [istio/ztunnel#608]
edit: the idea for the implementation here is inspired by https://github.com/envoyproxy/envoy/issues/20562

---

old, slightly confusing original context:

~it's not completely implemented, but what we do have is wrong.~ what we have is per-pod hostnames for statefulsets: https://github.com/istio/ztunnel/blob/9583efce62c8d9d4c29c987a6479d13803ea8149/src/dns/server.rs#L324-L331

we still need workload entry hostname support, which functions a bit differently.

the original intent behind the workload `hostname` field was to have a place to represent the [`WorkloadEntry.address`](https://istio.io/latest/docs/reference/config/networking/workload-entry/#WorkloadEntry) field, for example:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: details-svc
spec:
  # use of the service account indicates that the workload has a
  # sidecar proxy bootstrapped with this service account. Pods with
  # sidecars will automatically communicate with the workload using
  # istio mutual TLS.
  serviceAccount: details-legacy
  address: vm1.vpc01.corp.net # this would be the hostname on the workload we resolve via async polling
  labels:
    app: details-legacy
    instance-id: vm1
```

The new proposal after headless services support in ztunnel is to add a new `async_hostname` field for the WE hostname behavior.

The address field in the WorkloadEntry above translates to an [envoy DNS cluster](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery), and the workload hostname field in ztunnel was originally intended for this. Note that this means the DNS "cluster" in ztunnel here should use the system forwarder (any address field that's only in istio's DNS cache should return nxdomain to avoid potential looping DNS queries).

it's important we have some way for ztunnel to do DNS resolution as a client for workloads for geographic DNS resolution, e.g. https://github.com/istio/istio/blob/7bf52db38c91c89a4d56d6a94f402fd9ddaf6465/pilot/pkg/serviceregistry/kube/conversion.go#L151-L155

also note that the ztunnel DNS "cluster" implementation should likely mirror envoy's implementation as closely as possible to keep semantics the same for users. this also means we don't just want this lookup available for DNS proxy, but also need this to work during the request path (e.g. a service entry `se.istio.io` resolves to a workload with hostname `aws.elb.com` which resolves to final dest) by pre-resolving the provided hostnames asynchronously

cc @nmittler
