### ISSUE TITLE
Ambient mesh compatibility issues with k8s + ipvs

### ISSUE THREAD

**Issue by zengyuxing007** [istio/ztunnel#621]
Consider this path under Ambient:
```shell
   sleep -> ztunnel -> waypoint -> ztunnel -> reviews 
```

```shell
kubectl exec deployment/sleep -- curl reviews:9080/reviews/0
```
   
   reviews have v1 and v2 version ，we configured a vs and dr rule expecting 20% of the traffic to access v1 and 80% to access v2 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 20
    - destination:
        host: reviews
        subset: v2
      weight: 80
```

In a k8s cluster with ipvs turned on （(ambient mesh using iptables mode),  traffic rules such as the one above will not work.   because ipvs converts the request's destination ip to a pod ip in advance.

**Detail**：  The kube-proxy ipvs bind the ClusterIPs to kube-ipvs0 interface. The ClusterIPs will  add into local  route table which has more priority than ztunnel  rules. lead to ClusterIPs  traffics cannot hijack to ztunnel .

```shell
0:	from all lookup local <--- ipvs clusterips in local
100: from all fwmark 0x200/0x200 goto 32766
101: from all fwmark 0x100/0x100 lookup 101
102: from all fwmark 0x40/0x40 lookup 102
103: from all lookup 100
```

**How do we solve this issue?**

**Solution 1：**
  Hijack clusterIP requests to ztunnel properly by modifying (ip rule) routing rules in combination with some complex iptables rules. 

This solution needs to consider the compatibility of iptables and various  plugins, and it may not be user-friendly or easy to implement.

**Solution 2:**

There is a mapping table of pod and service vip under ztunnel, maybe we can make a compensation on the ztunnel side. 

In the scenario where the request target is a pod IP but the host/authority header field is a server name or VIP , we modify the target IP of the original request to a service VIP. The reason for additionally checking the host/authority header field is to distinguish the original pod IP request. 

 Of course, considering that ztunnel only handles 4 layers, we can use a simpler method to get the host/authority header without introducing the http/grpc parser sdk.

Or maybe there's a better solution? We can discuss it.

**Comment by zhlsunshine** [comment]
Hi @zengyuxing007, I think the problem should be that: the traffic shifting fails in ambient mode with Calico IPVS enabled in your k8s cluster. Am I right? Could you please provide more details about this issue. Such as uploading the YAML files of workloads, how to enable the IPVS in your environment etc ? Thanks!

**Comment by zengyuxing007** [comment]
A more optimal adaptation solution might be to provide compatibility and support on the wayPoint side.

Specifically, support for filter chain matcher rules similar to the following under main_internal listener.

```yaml
       "filter_chain_matcher": {
        "matcher_tree": {
         "input": {
          "name": "ip",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationIPInput"
          }
         },
         "custom_match": {
          "name": "ip",
          "typed_config": {
           "@type": "type.googleapis.com/xds.type.matcher.v3.IPMatcher",
           "range_matchers": [
          
            {
             "ranges": [
              {
               "address_prefix": "10.96.125.172",   
               "prefix_len": 32
              }
             ],
             "on_match": {
              "matcher": {
               "matcher_tree": {
                "input": {
                 "name": "port",
                 "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput"
                 }
                },
                "exact_match_map": {
                 "map": {
                  "1080": {
                   "action": {
                    "name": "inbound-vip|1080||reviews.default.svc.cluster.local-http",
                    "typed_config": {
                     "@type": "type.googleapis.com/google.protobuf.StringValue",
                     "value": "inbound-vip|1080||reviews.default.svc.cluster.local-http"
                    }
                   }
                  },
                  "9080": {
                   "action": {
                    "name": "inbound-vip|9080||reviews.default.svc.cluster.local-http",
                    "typed_config": {
                     "@type": "type.googleapis.com/google.protobuf.StringValue",
                     "value": "inbound-vip|9080||reviews.default.svc.cluster.local-http"
                    }
                   }
                  }
                 }
                }
               }
              }
             }
            },
            {
             "ranges": [  #### pod ip #####
              {
               "address_prefix": "10.244.1.7",
               "prefix_len": 32
              },
              {
               "address_prefix": "10.244.1.6",
               "prefix_len": 32
              },
              {
               "address_prefix": "10.244.1.9",
               "prefix_len": 32
              }
             ],
             "on_match": {
              "matcher": {
               "matcher_tree": {
                "input": {
                 "name": "application-protocol",
                 "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.ApplicationProtocolInput"
                 }
                },
                "exact_match_map": {
                 "map": {
                  "'h2c'": {
                   "matcher": {
                    "matcher_tree": {
                     "input": {
                      "name": "port",
                      "typed_config": {
                       "@type": "type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput"
                      }
                     },
                     "exact_match_map": {
                      "map": {
                       "1080": {
                        "action": {
                         "name": "direct-http-1080",
                         "typed_config": {
                          "@type": "type.googleapis.com/google.protobuf.StringValue",
                          "value": "direct-http-1080"
                         }
                        }
                       },
                       "9080": {
                        "action": {
                         "name": "direct-http-9080",
                         "typed_config": {
                          "@type": "type.googleapis.com/google.protobuf.StringValue",
                          "value": "direct-http-9080"
                         }
                        }
                       }
                      }
                     }
                    },
                    "on_no_match": {
                     "action": {
                      "name": "direct-http",
                      "typed_config": {
                       "@type": "type.googleapis.com/google.protobuf.StringValue",
                       "value": "direct-http"
                      }
                     }
                    }
                   }
                  },
                  "'http/1.1'": {
                   "matcher": {
                    "matcher_tree": {
                     "input": {
                      "name": "port",
                      "typed_config": {
                       "@type": "type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput"
                      }
                     },
                     "exact_match_map": {
                      "map": {
                       "1080": {
                        "action": {
                         "name": "direct-http-1080",
                         "typed_config": {
                          "@type": "type.googleapis.com/google.protobuf.StringValue",
                          "value": "direct-http-1080"
                         }
                        }
                       },
                       "9080": {
                        "action": {
                         "name": "direct-http-9080",
                         "typed_config": {
                          "@type": "type.googleapis.com/google.protobuf.StringValue",
                          "value": "direct-http-9080"
                         }
                        }
                       }
                      }
                     }
                    },
                    "on_no_match": {
                     "action": {
                      "name": "direct-http",
                      "typed_config": {
                       "@type": "type.googleapis.com/google.protobuf.StringValue",
                       "value": "direct-http"
                      }
                     }
                    }
                   }
                  }
                 }
                }
               },
               "on_no_match": {
                "action": {
                 "name": "direct-tcp",
                 "typed_config": {
                  "@type": "type.googleapis.com/google.protobuf.StringValue",
                  "value": "direct-tcp"
                 }
                }
               }
              }
             }
            }
           ]
          }
         }
        }
       }

```
The Pod IP branch can be based on port matching to enter the 7-layer routing (determined by VirtualHost).

Like this: 

```yaml

        {
         "filters": [
          {
           "name": "connect_authority",
           "typed_config": {
            "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
            "type_url": "type.googleapis.com/io.istio.http.connect_authority.Config"
           }
          },
          {
           "name": "envoy.filters.network.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
            "stat_prefix": "inbound_0.0.0.0_9080",
            "route_config": {
             "name": "encap",
             "virtual_hosts": [
              {
               "name": "inbound|http|9080",
               "domains": [
                "reviews.default.svc.cluster.local",
                "reviews",
                "reviews.default.svc",
                "reviews.default",
                "10.96.125.172"
               ],
               "routes": [
                {
                 "match": {
                  "prefix": "/"
                 },
                 "route": {
                  "weighted_clusters": {
                   "clusters": [
                    {
                     "name": "inbound-vip|9080|http/v1|reviews.default.svc.cluster.local",
                     "weight": 90
                    },
                    {
                     "name": "inbound-vip|9080|http/v2|reviews.default.svc.cluster.local",
                     "weight": 10
                    }
                   ]
                  },
                  "timeout": "0s",
                  "retry_policy": {
                   "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                   "num_retries": 2,
                   "retry_host_predicate": [
                    {
                     "name": "envoy.retry_host_predicates.previous_hosts",
                     "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
                     }
                    }
                   ],
                   "host_selection_retry_max_attempts": "5",
                   "retriable_status_codes": [
                    503
                   ]
                  },
                  "max_grpc_timeout": "0s"
                 },
                 "metadata": {
                  "filter_metadata": {
                   "istio": {
                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/reviews"
                   }
                  }
                 },
                 "decorator": {
                  "operation": "reviews:9080/*"
                 }
                }
               ]
              },
              {
               "name": "inbound|http|0",
               "domains": [
                "*"
               ],
               "routes": [
                {
                 "match": {
                  "prefix": "/"
                 },
                 "route": {
                  "cluster": "encap",
                  "timeout": "0s",
                  "max_stream_duration": {
                   "max_stream_duration": "0s",
                   "grpc_timeout_header_max": "0s"
                  }
                 },
                 "decorator": {
                  "operation": ":0/*"
                 },
                 "name": "default"
                }
               ]
              }
             ],
             "validate_clusters": false,
             "ignore_port_in_host_matching": true
            },
            "http_filters": [
             {
              "name": "envoy.filters.http.grpc_stats",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig",
               "emit_filter_state": true,
               "stats_for_all_methods": false
              }
             },
             {
              "name": "envoy.filters.http.fault",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault"
              }
             },
             {
              "name": "envoy.filters.http.cors",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"
              }
             },
             {
              "name": "istio.stats",
              "typed_config": {
               "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
               "type_url": "type.googleapis.com/stats.PluginConfig",
               "value": {
                "reporter": "SERVER_GATEWAY"
               }
              }
             },
             {
              "name": "envoy.filters.http.router",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
              }
             }
            ],
            "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 1
             },
             "overall_sampling": {
              "value": 100
             },
             "custom_tags": [
              {
               "tag": "istio.authorization.dry_run.allow_policy.name",
               "metadata": {
                "kind": {
                 "request": {}
                },
                "metadata_key": {
                 "key": "envoy.filters.http.rbac",
                 "path": [
                  {
                   "key": "istio_dry_run_allow_shadow_effective_policy_id"
                  }
                 ]
                }
               }
              },
              {
               "tag": "istio.authorization.dry_run.allow_policy.result",
               "metadata": {
                "kind": {
                 "request": {}
                },
                "metadata_key": {
                 "key": "envoy.filters.http.rbac",
                 "path": [
                  {
                   "key": "istio_dry_run_allow_shadow_engine_result"
                  }
                 ]
                }
               }
              },
              {
               "tag": "istio.authorization.dry_run.deny_policy.name",
               "metadata": {
                "kind": {
                 "request": {}
                },
                "metadata_key": {
                 "key": "envoy.filters.http.rbac",
                 "path": [
                  {
                   "key": "istio_dry_run_deny_shadow_effective_policy_id"
                  }
                 ]
                }
               }
              },
              {
               "tag": "istio.authorization.dry_run.deny_policy.result",
               "metadata": {
                "kind": {
                 "request": {}
                },
                "metadata_key": {
                 "key": "envoy.filters.http.rbac",
                 "path": [
                  {
                   "key": "istio_dry_run_deny_shadow_engine_result"
                  }
                 ]
                }
               }
              },
              {
               "tag": "istio.canonical_revision",
               "literal": {
                "value": "latest"
               }
              },
              {
               "tag": "istio.canonical_service",
               "literal": {
                "value": "bookinfo-reviews-istio-waypoint"
               }
              },
              {
               "tag": "istio.mesh_id",
               "literal": {
                "value": "cluster.local"
               }
              },
              {
               "tag": "istio.namespace",
               "literal": {
                "value": "default"
               }
              }
             ]
            },
            "server_name": "istio-envoy",
            "use_remote_address": false,
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             }
            ],
            "stream_idle_timeout": "0s",
            "normalize_path": true,
            "request_id_extension": {
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig",
              "use_request_id_for_trace_sampling": true
             }
            },
            "path_with_escaped_slashes_action": "KEEP_UNCHANGED"
           }
          }
         ],
         "name": "direct-http-9080"
        }

```
