### ISSUE TITLE
DNS incorrect treats all services without VIP as headless

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#909]
A config like:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
  annotations:
    istio.io/use-waypoint: default
spec:
  hosts:
  - address.baz
  location: MESH_INTERNAL
  ports:
  - name: http-0
    number: 80
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: echo
```

will resolve to all "echo" Pod IPs. This is not expected. It should NXDOMAIN (assuming no auto allocation enabled)
